server:
  port: 22976

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2345/studs
    username: postgres
    password: bgi855

  jpa:
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /api
